Eeek/config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :users, path: "", controllers: { sessions: "login", registrations: "login" }, :skip =>     [:sessions, :registrations], :path_names => { :sign_up => "/", :sign_in => "/" }
  # devise_for :users, path: "", controllers: { sessions: "users", registrations: "users" }, path_names: { sign_in: '/', password: '/', confirmation: '/', unlock: '/', sign_up: '/', sign_out: '/'}
 
 


  root 'login#index'

  resources :users, only: [:create, :destroy, :update]
  resources :feed
  resources :dashboard, only: [:index]
  resources :home, only: [:index]
  resources :mood, only: [:create]

  resources :uploads, only: [:new, :create, :destroy]
  
  resources :contacts, only: [:create, :new, :destroy, :update, :index]




  post 'users/login' => "users#login"
  get 'uploads/trigger' => "uploads#trigger"


  # GoogleAuthExample::Application.routes.draw do
  #   get 'auth/:provider/callback', to: 'sessions#create'
  #   get 'auth/failure', to: redirect('/')
  #   get 'signout', to: 'sessions#destroy', as: 'signout'

  #   resources :sessions, only: [:create, :destroy]
  #   resource :home, only: [:show]

  #   root to: "home#show"
  # end

  get '*path' => redirect('/')

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

Eeek/app/controllers/login_controller.rb
class LoginController < ApplicationController

	def index
		if user_signed_in?
			redirect_to :controller => 'home', :action => 'index'
		end
	end

	private

	def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

Eeek/app/views/login/_login_form.html.erb
<div class="login_div">

      
  <p>Or sign in the old fashion way. Ya <span id="dinosaur_word">dinosaur.</span></p>

	<div class="error_messages"><%= flash[:error] %></div>
	<%= form_tag users_login_path, method: :post, :html => {:class => "login_form"} do %>
	  <%= text_field_tag :email, "", placeholder: 'Email' %>
	  <%= password_field_tag :password, "", placeholder: "Password" %>
	  <%= submit_tag("login") %>
	<% end %>

</div>

Eeek/app/views/login/_sign_up_form.html.erb
<div class="signup_div">
	<h1 class="signup_form_header">Don't have an account? <button id="signup_form_display_button">Sign Up</button></h1>
    <div class="error_messages"><%= session[:sign_up_error] if session[:sign_up_error] %></div>
		

		<%= form_for :user, url: users_path, method: :post, :html => {:class => "signup_form"} do |f| %>
			<%= f.text_field :name, :placeholder => "What's your first name?" %>
			<%= f.text_field :email, :placeholder => "Email" %>
			<%= f.password_field :password, :placeholder => "Password, shhh" %>
			<%= f.password_field :password_confirmation, :placeholder => "Confirm your password" %>
			<%= submit_tag("sign up") %>
		<% end %>        
	
</div>

Eeek/app/views/login/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
 <div class="outermost">

    <div class="clouds cloud_1"> </div>
    <div class="clouds cloud_2"> </div>
    <div class="clouds cloud_3"> </div>
    <div class="clouds cloud_4"> </div>
    <div class="clouds cloud_5"> </div>
    <div class="clouds cloud_6"> </div>
    <div id="dinosaur_icon"></div>


    <div class="login_page">

      <h1 class="eeek_title">Eeek.</h1>
      <%= link_to "<div class='social-google'></div>".html_safe, user_omniauth_authorize_path(:google_oauth2), class: "social-google" %>
      <% if @errors %>
        <% @errors.each do |attribute, error| %>
          <p>Oh No! <%="#{attribute.capitalize}  #{error}" %></p>
          <div><%= resource.errors.inspect %></div>
        <% end %>
      <% end %>
      <%= render 'login_form' %>      
      <%= render 'sign_up_form' %>
    </div>
    
 </div> 