Eeek/config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :users, path: "", controllers: { sessions: "login", registrations: "login" }, :skip =>     [:sessions, :registrations], :path_names => { :sign_up => "/", :sign_in => "/" }
  # devise_for :users, path: "", controllers: { sessions: "users", registrations: "users" }, path_names: { sign_in: '/', password: '/', confirmation: '/', unlock: '/', sign_up: '/', sign_out: '/'}
 
 


  root 'login#index'

  resources :users, only: [:create, :destroy, :update]
  resources :feed
  resources :dashboard, only: [:index]
  resources :home, only: [:index]
  resources :mood, only: [:create]

  resources :uploads, only: [:new, :create, :destroy]
  
  resources :contacts, only: [:create, :new, :destroy, :update, :index]




  post 'users/login' => "users#login"
  get 'uploads/trigger' => "uploads#trigger"


  # GoogleAuthExample::Application.routes.draw do
  #   get 'auth/:provider/callback', to: 'sessions#create'
  #   get 'auth/failure', to: redirect('/')
  #   get 'signout', to: 'sessions#destroy', as: 'signout'

  #   resources :sessions, only: [:create, :destroy]
  #   resource :home, only: [:show]

  #   root to: "home#show"
  # end

  get '*path' => redirect('/')

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

Eeek/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController 
	
  before_filter :authenticate_user!

	def index
    @user = current_user
    @uploads = Upload.where(user_id: @user.id)
    @user_uploads = []
    @complimentary_uploads = []
    @uploads.each do |upload| 
      if upload.complimentary == "true" 
        @complimentary_uploads << upload
      else
        @user_uploads << upload
      end
    end
  end


end

Eeek/app/views/dashboard/_resources.html.erb
<div class="resources_wrapper">
	<h1 class="resources_header">
		Some Resources If You Need Them
	</h1>
	<ul>
		<li><a href="http://www.suicidepreventionlifeline.org/">The National Suicide Prevention Lifeline</a> -- 1-800-273-8255 or click <a href="http://www.suicidepreventionlifeline.org/GetHelp/LifelineChat.aspx">here for online chat.</a></li>
	</ul>
	<ul>
		<li><a href="https://ncadd.org/">National Council on Alcoholism and Drug Dependence Hopeline</a> -- (800) 622-2255</li>
	</ul>
	<ul>
		<li><a href="http://www.translifeline.org/">The TransLifeLine</a> -- US: 877-565-8860, Canada: 877-330-6366. For trangender related issues.</li>
	</ul>
	<ul>
		<li><a href="http://www.lgbt.ie/">LGBT Helpline</a> -- 1-890-929-539.</li>
	</ul>
	<ul>
		<li><a href="http://www.veteranscrisisline.net/ChatTermsOfService.aspx?account=Veterans%20Chat">The Veterans Crisis Line</a> -- 1-800-273-8255 or text 838255 or online chat available on their homepage.</li>
	</ul>
	<ul>
		<li><a href="http://www.stopbullying.gov/">StopBullying.gov</a> -- For support being bullied.</li>
	</ul>
	<ul>
		<li><a href="https://www.childhelp.org/">National Child Abuse Hotline</a> -- 1-800-422-4453 </li>
	</ul>
	<ul>
		<li><a href="http://www.thehotline.org/">The National Domestic Violence Hotline</a> -- 1-800-799-7233</li>
	</ul>
	<ul>
		<li><a href="http://www.nationaleatingdisorders.org/">The National Eating Disorders Association</a> -- 1-800-931-2237</li>
	</ul>
	<ul>
		<li><a href="http://www.1800runaway.org/">The National Runaway Safeline</a> -- 1-800-786-2929, for if you are running away.</li>
	</ul>

</div>

Eeek/app/views/dashboard/_thumbnail.html.erb
<li class="thumbnail_li" id=<%="#{upload.id}_thumbnail"%>>
	<% if upload.text %>
		<p class="thumbnail text_thumbnail"><%= upload.text %></p>
		<%= link_to "Delete", upload_path(upload), method: :delete, class: "delete_button", :remote => true  %>
	<% else  %>
		<img src=<%= upload.attachment %> class="thumbnail">
		<%= link_to "Delete", upload_path(upload), method: :delete, class: "delete_button", :remote => true %>
	<% end %>
</li>

Eeek/app/views/dashboard/_top_bar.html.erb
    <div class="omnii-header">
      <nav>
          <div class="menu_icon"></div>
        <ul>
          <li><a href="/home" class="logo home_menu_item">Home</a></li>
          <li><a href="/dashboard" class="logo dashboard_menu_item">Eeek</a></li>
          <li><a href="/uploads" class="logo uploads_menu_item">Dashboard</a></li>
           <li>
            <div class="open-right">
              <a href="#" id="upload_button"><%="New Upload"%></a>
            </div>
          </li>
          <li>
            <%= link_to destroy_user_session_path, :method => :delete do %>Logout<% end %>
          </li>
        </ul>
      </nav>
    </div>







  

Eeek/app/views/dashboard/index.html.erb
<%= render partial: "feed/top_bar" %>

<%= render partial: 'uploads/upload_form' %>

<div class="upload_index_wrapper">




 	<div class="graph_div">
 		<h3>Your mood trend</h1>
		<% if Rails.env.production? %>
			<%= line_chart current_user.moods.group(:created_at).maximum(:scale) %>
		<% else %>
			<%= line_chart current_user.moods.group(:created_at).maximum(:scale) %>
		<% end %>
	</div>

	<hr>

	<h1> All of your things here </h1>

		<ul class="thumbnail_ul personal_ul">
			<% if @user_uploads && @user_uploads.length > 0 %>
				<% @user_uploads.each do |upload| %>
					<li class="thumbnail_li" id=<%="#{upload.id}_thumbnail"%>>
						<!-- <h3 class="hidden_thumbnail_message">Click to enlarge</h3> -->
						<% if upload.text %>
							<p class="thumbnail text_thumbnail"><%= upload.text %></p>
							<%= link_to "Delete", upload_path(upload), method: :delete, class: "delete_button", :remote => true  %>
						<% else  %>
							<img src=<%= upload.attachment %> class="thumbnail">
							<%= link_to "Delete", upload_path(upload), method: :delete, class: "delete_button", :remote => true %>
						<% end %>
					</li>
				<% end %>
			<% else %>
				<hr>
				<p class="nothing_yet">You haven't uploaded anything yet! <br> Click the 'new upload' link in the top bar to get started.</p>
			<% end %>
		</ul>
		<br>
		<hr>
		<br>
	<h1> All of the things that came with your account here </h1>
		<ul class="thumbnail_ul">
			<% @complimentary_uploads.each do |upload| %>
				<li class="thumbnail_li" id=<%="#{upload.id}_thumbnail"%>>
					<h3 class="hidden_thumbnail_message">Click to enlarge</h3>
					<% if upload.text %>
						<p class="thumbnail text_thumbnail"><%= upload.text %></p>
						<%= link_to "Delete", upload_path(upload), method: :delete, class: "delete_button", :remote => true  %>
					<% else  %>
						<img src=<%= upload.attachment %> class="thumbnail">
						<%= link_to "Delete", upload_path(upload), method: :delete, class: "delete_button", :remote => true  %>
					<% end %>
				</li>
			<% end %>
		</ul>

</div>

<hr>

<%= render partial: 'resources' %>

<%= render partial: 'home/footer' %>