Eeek/config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :users, path: "", controllers: { sessions: "login", registrations: "login" }, :skip =>     [:sessions, :registrations], :path_names => { :sign_up => "/", :sign_in => "/" }
  # devise_for :users, path: "", controllers: { sessions: "users", registrations: "users" }, path_names: { sign_in: '/', password: '/', confirmation: '/', unlock: '/', sign_up: '/', sign_out: '/'}
 
 


  root 'login#index'

  resources :users, only: [:create, :destroy, :update]
  resources :feed
  resources :dashboard, only: [:index]
  resources :home, only: [:index]
  resources :mood, only: [:create]

  resources :uploads, only: [:new, :create, :destroy]
  
  resources :contacts, only: [:create, :new, :destroy, :update, :index]




  post 'users/login' => "users#login"
  get 'uploads/trigger' => "uploads#trigger"


  # GoogleAuthExample::Application.routes.draw do
  #   get 'auth/:provider/callback', to: 'sessions#create'
  #   get 'auth/failure', to: redirect('/')
  #   get 'signout', to: 'sessions#destroy', as: 'signout'

  #   resources :sessions, only: [:create, :destroy]
  #   resource :home, only: [:show]

  #   root to: "home#show"
  # end

  get '*path' => redirect('/')

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

Eeek/app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :contact_name, presence: true
  validates :phone_number, presence: true
  validates :phone_number, format: { with: /\A\d{10}\z/i}

	belongs_to :user
end

Eeek/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	# def index
	# 	p "index" * 50
	# end

	# def create
	# 	@contact = Contact.new(contact_params)
	# 	@contact.user_id = current_user.id
	# 	respond_to do |format|
	# 		if @contact.save
	# 			format.js { render :create_contact_success }
	# 		else
	# 			format.js { render :create_contact_fail }
	# 		end
	# 	end
	# end

	# def new
	# 	respond_to do |format|
	# 			format.js { render :render_new_contact_form }
	# 	end
	# end

	# def update
	# end

	# def destroy
	# end

	# private
 
 #  def contact_params
 #    params.require(:contact).permit(:contact_name, :phone_number, :user_id)
 #  end


end

Eeek/app/views/contacts/_new_contact_form.html.erb
<div class="form new_contact_form_div">
  <h1>New Contact</h1>

 	<%= form_for :contact, :url => contacts_path, :action => :create, :method => :post, html: { id: "new_contact_form" }, remote: true do |f| %>
 		<hr>
    <%= f.label :j, id: "icon"%>
    <%= f.text_field :contact_name, id: "name", value: "", placeholder: "Contact's Name"%>
    <%= f.label :phone_number, id: "icon"%>
    <%= f.text_field :phone_number, id: "name", value: "", placeholder: "XXXXXXXXXX" %>
    <hr>
    <p>Note: This contact must be able to recieve text messages.</p>
    <%= f.submit "Save", class: "button" %>
  <% end %>
</div>

Eeek/app/views/contacts/create_contact_fail.js.erb
alert("create_contact_fail.js.erb")

Eeek/app/views/contacts/create_contact_success.js.erb
alert("create_contact_success.js.erb");

Eeek/app/views/contacts/render_new_contact_form.js.erb
$(".render_form_target_div").append("<%= j (render 'new_contact_form') %>");